### ISSUE TITLE
Add some example script please!!

### ISSUE THREAD

**Issue by ShalolaAuthor** [PrincessRTFM/WoLua#3]
i cant quite figure out how to actually use this.

**Comment by PrincessRTFM** [comment]
I'll see what I can do, although in the meantime you can look at some (actual, released) scripts I've written here:
- [battlemode](https://github.com/PrincessRTFM/WoLua.battlemode) toggle your weapon draw state using the fancier `/draw` and `/sheathe` emotes, when possible
- [gearsnap](https://github.com/PrincessRTFM/WoLua.gearsnap) changes gearsets just like `/gearset change` does, but uses the `/snap` emote first and times it for a "magical outfit change" effect
- [isort](https://github.com/PrincessRTFM/WoLua.isort) is an admittedly very complicated one-line-able multi-inventory sorting handler
- [random](https://github.com/PrincessRTFM/WoLua.random) lets you create lists of arbitrary text and pick one item from a given list at random, in various ways - including use in or _as_ commands, which can be used for things like random collections of minions or mounths

If the problem is that you don't know lua, then I'd recommend looking online for some basic tutorials. If the problem is not knowing the WoLua API, that's [documented on here](https://github.com/PrincessRTFM/WoLua/blob/master/docs/README.md). If you don't know where to put your scripts, then that _should_ be documented, but I might not've been clear enough so let me know.

**Comment by ShalolaAuthor** [comment]
> Not done yet, there'll be more, but hopefully that helps.

thats sick!! thanks a lot :)

**Comment by PrincessRTFM** [comment]
This has been put on a slight hold as I work on a system for generating lua docs and linting references, but this (and that) will be coming Eventually:tm:.
